### ISSUE TITLE
RuntimeWarning: invalid value encountered in sqrt   return distances if squared else np.sqrt(distances, out=distances)

### ISSUE THREAD

**Issue by kalybz** [achilleas96/rbfn-with-tensorflow#1]
when I run rbfn.py ,I meet a error that "RuntimeWarning: invalid value encountered in sqrt   return distances if squared else np.sqrt(distances, out=distances)",Then my code is stop,but not out ,Can you give me some advice ? thanks very much.

**Comment by achilleas96** [comment]
This is the first time i see that error, i had run it more than  15 times for different values of k and no problem occurred. Make sure that you are using python 3.6.x
